### ISSUE TITLE
Future LICENSE.md?

### ISSUE THREAD

**Issue by grandamp** [grandamp/apigw-custom-auth-mtls#1]
@kmkale thoughts?

I appreciate the time you took to document an mTLS lambda authorizer.

Would you mind if I assign a license.md file that asserts https://creativecommons.org/publicdomain/zero/1.0/legalcode ?

Of course, I'm happy to provide any attribution back to your work, but; do not want to muddle your public example with the [U.S. Federal PKI](https://playbooks.idmanagement.gov/fpki/)

**Comment by kmkale** [comment]
I don't mind at all @grandamp

**Comment by grandamp** [comment]
Thanks!
